--- # Ergex config file for pilot data

# This file allows control over the data processing pipeline without any need
# to edit the code.

# This section specifies the folder structure
data directoty: "data/1_pilot"
figure directoty: "figs/1_pilot"

# This section specifies data variables
data_variant: "1_pilot"

simulation_varaints: " "

# This section specifies plotting variables
colors: ["#e28743", "#043d74"]

# This section provides control over whether data needs to be re-read
readingdata:
  run: False

# This section provides control over whether plot data needs to be re-calculated
plot_data:
  run: False
  calculate_indif_eta: False
  log_reg: True
  bayesian: True

# This section provides control over the various steps in the plotting pipeline
plots:
  run: True
