--- # Ergex config file

# This file allows control over the data processing pipeline without any need
# to edit the code.

# This section specifies the folder structure
simulation_varaints: ["160", "1000"]
data_folders: ["data/0_simulation/n_160", "../data/0_simulation/n_1000"]
fig_folders: ["figs/0_simulation/n_160", "../figs/0_simulation/n_1000"]

# This section specifies data variables
data_variant: "0_simulation"
n_agents: 10
etas: [0.0, 0.5, 1.0]

# This section specifies plotting variables
colors: ["#e28743", "#043d74"]

# This section provides control over the various steps in the readingdata pipeline
readingdata:
  run: True

  stages:
    passive_output: False
    active_output: True
    include indif eta: True #assumes above is true
    output .mat: true

# This section provides control over the various steps in the plotting pipeline
plots:
  run: True
  figures:
    subject wise: False
    group mean: False
    simulation overview: True
