name: ergex
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.9
  - r-base=4.3.1
  - r-bayesfactor=0.9.12
  - r-optparse=1.7.3
  - r-lsr=0.5.2
  - r-ggplot2=3.4.2
  - r-devtools=2.4.5
  - r-stargazer=5.2.3
  - r-bas=1.7.1
  - pip
  - pip:
    - -r requirements.txt
