--- # Ergex config file for simulation 1

# This file allows control over the data processing pipeline without any need
# to edit the code.

# This section specifies the folder structure
data directoty: "data/0_simulation/grid/eta_10"
figure directoty: "figs/0_simulation/grid/eta_10"

# This section specifies data variables
data_type: "0_simulation"
data_variant: "grid"

# This section provides control over whether data needs to be re-read
readingdata:
  run: True

# This section provides control over whether plot data needs to be re-calculated
bracketing method:
  run: False
  calculate_indif_eta: True
  log_reg: True

# This section provides control over the various steps in the plotting pipeline
plots:
  run: False
