--- # Ergex config file for simulation 1

# This file allows control over the data processing pipeline without any need
# to edit the code.

# This section specifies the folder structure
data directory: "data/0_simulation/grid/eta_05"
figure directory: "figs/0_simulation/grid/eta_05"

# This section specifies data variables
data_type: "0_simulation"
data_variant: "grid"
sim_version : 3
n_agents: 10
qual: 3
n_conditions: 2

# This section provides control over whether data needs to be re-read
readingdata:
  run: True

# This section provides control over whether user wants to re-run the Bayesian models
bayesian method:
  run: True

# This section provides control over whether plot data needs to be re-calculated
bracketing method:
  run: True
  calculate_indif_eta: True
  log_reg: True

# This section provides control over whether user wants to re-compute the JASP input
JASP input:
  run: False
bayesfactor_analysis:
  plot: false
  run: false
  target: partial_pooling

# This section provides control over the various steps in the plotting pipeline
plots:
  run: False
  plot_passive: True
  plot_no_brainers: True
  plot_active: True
  plot_riskaversion_bracketing: True
  plot_riskaversion_bayesian: True
